@startuml
'https://plantuml.com/state-diagram

scale 580 width
hide empty description

[*] --> STATE_INIT
STATE_INIT --> STATE_REACHABLE : EVENT_SERVER_REACHABLE
STATE_INIT --> STATE_NOT_REACHABLE : EVENT_SERVER_NOT_REACHABLE

STATE_REACHABLE --> STATE_NOT_REACHABLE : EVENT_SERVER_NOT_REACHABLE
STATE_NOT_REACHABLE --> STATE_RECOVERY : EVENT_SERVER_REACHABLE
STATE_RECOVERY --> STATE_REACHABLE : EVENT_SERVER_REACHABLE
STATE_RECOVERY --> STATE_NOT_REACHABLE : EVENT_SERVER_NOT_REACHABLE

@enduml